version: '3.9'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "3023:3023"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/brickstorage/bin/migrate up && /brickstorage/bin/api" ]
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=brickstorage_db
      - POSTGRES_USER=brickstorage_user
      - POSTGRES_PASSWORD=brickstorage_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U brickstorage_user -d brickstorage_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always