apiVersion: apps/v1
kind: Deployment
metadata:
  name: brickstorage-app
  namespace: brickstorage
  labels:
    app: brickstorage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brickstorage-app
  template:
    metadata:
      labels:
        app: brickstorage-app
    spec:
      containers:
      - name: brickstorage-app
        image: learningcloudnativego/brickstorage-app:0.0.1
        imagePullPolicy: IfNotPresent
        command: ["/brickstorage/api"]
        ports:
        - name: httpport
          containerPort: 3023
        envFrom:
        - configMapRef:
            name: brickstorage-app-config
        - secretRef:
            name: brickstorage-app-secret
        readinessProbe:
          httpGet:
            path: /livez
            port: 3023
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: 3023
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"