apiVersion: v1
kind: Service
metadata:
  name: brickstorage-app
  namespace: brickstorage
  labels:
    app: brickstorage-app
spec:
  ports:
  - port: 8001
    targetPort: httpport
    name: http
  selector:
    app: brickstorage-app