apiVersion: v1
kind: Secret
metadata:
  name: brickstorage-app-secret
  namespace: brickstorage
  labels:
    app: brickstorage-app-secret
type: Opaque
data:
  DB_PASS: 'VE9ETzogVXBkYXRlIGFjY29yZGluZyB0byBwcm9kdWN0aW9uIGVudg==' # TODO: Update according to production env